import type { DecisionSignal } from "./decisionTypes";

export const relationshipRules: DecisionSignal[] = [
  {
    id: "sales_up_mer_down",
    title: "Revenue growing but efficiency weakening",
    severity: "warning",
    lane: "risk",
    entityLevel: "account",
    confidenceFlag: "High",
    actionType: "Protect",
    priorityFactors: {
      businessImpact: 95,
      urgency: 90,
      confidence: 80,
      persistence: 70,
      scope: 85,
      riskWeight: 100,
    },
    diagnosis: "Spend is increasing faster than business growth.",
    recommendation: "Audit Google and TikTok before scaling further.",
  },
  {
    id: "creative_fatigue",
    title: "Creative fatigue risk",
    severity: "danger",
    lane: "risk",
    entityLevel: "campaign",
    confidenceFlag: "High",
    actionType: "Refresh",
    priorityFactors: {
      businessImpact: 72,
      urgency: 80,
      confidence: 70,
      persistence: 65,
      scope: 70,
      riskWeight: 85,
    },
    diagnosis: "Audience saturation detected with weak engagement.",
    recommendation: "Launch new hooks, angles, and creatives immediately.",
  },
  {
    id: "traffic_quality_issue",
    title: "Traffic quality issue",
    severity: "danger",
    lane: "risk",
    entityLevel: "campaign",
    confidenceFlag: "Medium",
    actionType: "Refine",
    priorityFactors: {
      businessImpact: 68,
      urgency: 78,
      confidence: 72,
      persistence: 60,
      scope: 65,
      riskWeight: 75,
    },
    diagnosis: "Clicks are coming through, but post-click behavior suggests low-intent traffic.",
    recommendation: "Refine targeting, placements, and messaging alignment before pushing more spend.",
  },
  {
    id: "checkout_failure",
    title: "Checkout failure risk",
    severity: "danger",
    lane: "risk",
    entityLevel: "account",
    confidenceFlag: "High",
    actionType: "Fix",
    priorityFactors: {
      businessImpact: 96,
      urgency: 94,
      confidence: 88,
      persistence: 75,
      scope: 92,
      riskWeight: 100,
    },
    diagnosis: "Purchase intent is present, but users are breaking in the checkout flow.",
    recommendation: "Audit checkout completion, payment errors, and friction before making budget decisions.",
  },
  {
    id: "tracking_mismatch",
    title: "Tracking mismatch active",
    severity: "danger",
    lane: "risk",
    entityLevel: "account",
    confidenceFlag: "High",
    actionType: "Verify",
    priorityFactors: {
      businessImpact: 82,
      urgency: 88,
      confidence: 95,
      persistence: 72,
      scope: 90,
      riskWeight: 95,
    },
    diagnosis: "Platform reporting and backend truth are not aligned enough to trust scaling decisions.",
    recommendation: "Audit pixel, CAPI, deduplication, and backend conversion reconciliation first.",
  },
  {
    id: "safe_scaling_opportunity",
    title: "Safe scaling opportunity",
    severity: "healthy",
    lane: "opportunity",
    entityLevel: "campaign",
    confidenceFlag: "Medium",
    actionType: "Scale",
    priorityFactors: {
      businessImpact: 45,
      urgency: 35,
      confidence: 80,
      persistence: 60,
      scope: 70,
      opportunityWeight: 80,
    },
    diagnosis: "Account efficiency is stable across acquisition and blended performance.",
    recommendation: "Scale Meta gradually by 10-15%.",
  },
] as const;