"use client";
import { useCallback, useEffect, useState } from "react";
type Status = { connected: boolean; missingEnv: string[]; accounts: Array<{ adAccountId: string; adAccountName: string }>; selectedAccountId: string | null; tokenExpired: boolean; mappingHealthy: boolean; connectionError: string | null };
const field = "w-full rounded-xl border border-[var(--line)] bg-white/80 px-3 py-2 text-sm", button = "rounded-xl bg-[var(--accent)] px-4 py-2 text-sm font-semibold text-white", secondary = "rounded-xl border border-[var(--line)] bg-white px-4 py-2 text-sm font-semibold";
export function SnapAdsSetup({ clientId }: { clientId: string }) {
  const [status, setStatus] = useState<Status | null>(null), [accountId, setAccountId] = useState(""), [message, setMessage] = useState("");
  const load = useCallback(async () => { const response = await fetch(`/api/integrations/snap/status?clientId=${encodeURIComponent(clientId)}`, { cache: "no-store" }), payload = await response.json() as Status & { error?: string }; if (!response.ok) return setMessage(payload.error ?? "Could not load Snapchat status."); setStatus(payload); setAccountId(payload.selectedAccountId ?? payload.accounts[0]?.adAccountId ?? ""); }, [clientId]);
  useEffect(() => { const task = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(task); }, [load]);
  async function save() { const response = await fetch(`/api/integrations/snap/accounts?clientId=${encodeURIComponent(clientId)}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ adAccountId: accountId }) }), payload = await response.json() as { error?: string }; setMessage(response.ok ? "Snap ad account saved." : payload.error ?? "Save failed."); if (response.ok) await load(); }
  async function discover() { const response = await fetch(`/api/integrations/snap/events-preview?clientId=${encodeURIComponent(clientId)}`, { cache: "no-store" }), payload = await response.json() as { events?: unknown[]; error?: string }; setMessage(response.ok ? `Loaded ${payload.events?.length ?? 0} supported Snap conversion metrics. Select them in the shared mapping panel.` : payload.error ?? "Discovery failed."); }
  return <section id="snap-connection" className="rounded-[18px] border border-[var(--line)] bg-white/58 p-4">
    <div className="flex flex-wrap items-start justify-between gap-3 border-b border-[var(--line)] pb-3"><div><div className="text-[11px] font-semibold uppercase tracking-[.14em] text-[var(--muted)]">Paid Social</div><h2 className="mt-1 text-lg font-semibold">Snapchat</h2><p className="mt-1 text-sm text-[var(--muted)]">Implemented, awaiting live validation.</p></div><span className="rounded-full border px-2 py-1 text-xs font-semibold">{status?.connected ? status.tokenExpired ? "Token expired" : "Connected" : "Awaiting connection"}</span></div>
    <select className={`mt-4 ${field}`} value={accountId} onChange={(event) => setAccountId(event.target.value)}><option value="">Choose ad account</option>{(status?.accounts ?? []).map((item) => <option key={item.adAccountId} value={item.adAccountId}>{item.adAccountName} · {item.adAccountId}</option>)}</select>
    <div className="mt-3 flex flex-wrap gap-2"><a className={button} href={`/api/integrations/snap/connect?clientId=${encodeURIComponent(clientId)}`}>{status?.connected ? "Reconnect Snapchat" : "Connect Snapchat"}</a><button className={secondary} type="button" disabled={!accountId} onClick={() => void save()}>Save account</button><button className={secondary} type="button" onClick={() => void discover()}>Discover conversions</button></div>
    {status?.missingEnv.length ? <div className="mt-3 text-sm text-amber-800">External setup deferred: {status.missingEnv.join(", ")}</div> : null}<div className="mt-2 text-xs text-[var(--muted)]">Mapping: {status?.mappingHealthy ? "healthy" : "missing"}{status?.connectionError ? ` · ${status.connectionError}` : ""}</div>{message ? <div className="mt-3 rounded-xl border px-3 py-2 text-sm">{message}</div> : null}
  </section>;
}
